## Надо исправить

- Добавление карточек не работает, в script есть комментарии почему 

- Если обратите внимание, когда выключена сеть, у вас при отправке данных на сервер окно не закрывается (что хорошо), но ошибка которую вы в консоли выводите -- это ошибка, которую вы получили не в Api, а в точке вызова. 
Поясняю: Api обратился к серверу, сервер не доступен, поэтому в then метода обращения мы даже не попадаем и нас перебрасывает в catch метода Api. Вроде все хорошо? Не совсем. Если бы вы __внимательно__  посмотрите в прошлые ревью, то увидите что я рекомендовал из catch возвращать Promise.reject -- почему?

Потому что console.log(err) -- это не обработка ошибки и уж тем более не информирование скрипта об ошибке, это просто вывод в консоль. Поэтому catch метода Api возвращает undefined значение, которое (т.к. система об ошибке после catch не знает, у него же в вашей реализации нет return) попадает сразу в then в основном скрипте, где вы пытаетесь что-то сделать с полученным result, который undefined (ведь именно такое значение передает любая функция без return). И в catch точки вызова вы попадаете, не потому что Api классно отработал, а потому что возникла ошибка работы с необределенным result. Если убрать catch в точке вызова, то скрипт просто упадет.

Итак, каждый catch Api может что угодно писать в консоль. Но заканчиваться он должен хотя бы так: return Promise.reject('Какой-то текст ошибки')
Исправьте это.

- см. комментарии в Card, CardList, popup и script.

## Промежуточный итог

Тут вроде и немного осталось, но все же внимательность не повредит, много новых ошибок получилось в этот раз. Если есть сложности с реализацией, попросите помощи наставника, хотя я достаточно подробно все пояснил. Исправьте критические замечания и присылайте на проверку.
