Добрый день. 

Базовый набор функций работает, класс Api создан, но тем не менее есть замечания:

## Надо исправить

- В классе Api catch для ошибок должен быть у каждого метода, который с сервером работает. Причина в том, что мы не знаем обрабатывает ли кто-то ошибки в точке вызова, поэтому класс должен как минимум сам об ошибке сообщить.

- Catch в методе Api должен либо пробрасывать ошибку через throw, либо возвращать промис с ошибкой, потому что в месте вызова метода должно быть четко понятно, что вернул Api -- успешный ответ или ошибку.

- Полученный ответ от метода экземпляра Api тоже нужно принять через then и catch.

Допустим у вас есть метод Api:
~~~
someApiMethod() {
  return fetch(...)
          .then(...)
          .catch(...) // возвращает reject
}
~~~
В точке вызова действуем так:
~~~
api.someApiMethod()
  .then(... что-то рисуем, меняем, закрываем)
  .catch(... ничего не меняем, не закрываем, сообщаем об ошибке)
~~~

Вы всю первичную проверку перекинули с интерфейса Api на точку вызова, зачем тогда такой класс нам нужен? Обертка вокруг fetch? Наша задача создать интерфейс общения с сервером, который __обязан__ проверить статус ответа: и на res.ok и иметь свой catch и т.д. Это надо реализовать.

- Исправьте классы Card, CardList и замечания по этим классам в script.js -- посмотрите на схему их взаимодействия, она сложна и запутана, передаете массу параметров но часть не используется, у другой части имена могли быть удачнее. В комментариях я отразил суть проблемы.

- Прочие комментарии в script.js

## Промежуточный итог

Работа улучшилась, но все еще требует рефакторинга. Исправьте критические замечания и присылайте на проверку.
